# Generated by Django 4.0.2 on 2022-03-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_rename_like_likes_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
            ],
        ),
    ]
